### ISSUE TITLE
Distribution Not Found

### ISSUE THREAD

**Issue by ruffsl** [osrf/rocker#12]
Perhaps this is something to do with my system, but after installing rocker through apt on Ubuntu 18.04, I seem be getting this error: 

```
$ rocker --nvidia --user --pull --pulse osrf/ros:crystal-desktop rviz2
Traceback (most recent call last):
  File "/usr/bin/rocker", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'distro' distribution was not found and is required by rocker
```

This didn't seem to resolve the issue above:
https://stackoverflow.com/a/6200314

More info:

```
$ apt show python3-rocker 
Package: python3-rocker
Version: 0.0.1-100
Priority: optional
Section: python
Maintainer: Tully Foote <tfoote@osrfoundation.org>
Installed-Size: 48.1 kB
Depends: python3-empy, python3-pexpect, python3-requests, python3:any (>= 3.2~), python3-docker
Conflicts: python-rocker
Download-Size: 7,584 B
APT-Manual-Installed: yes
APT-Sources: http://packages.ros.org/ros/ubuntu bionic/main amd64 Packages
Description: A tool to run docker containers with customized extras
 A tool to run docker containers with customized extra added like nvidia gui support overlayed.
```

**Comment by tfoote** [comment]
If you're running on xenial you'll need to manually install python3-distro https://github.com/osrf/rocker#debians

I've added the dependency to 0.1.3 and that deb is propogating at the moment.

**Comment by tfoote** [comment]
WIth the backport instructions it will work from debs, and with a pip install it will get the dependency automatically. I'm going to close this as resolved.

**Comment by yuqli** [comment]
@tfoote Thanks for your comment on `pip install docker-py` this helps my issue!!! Do you have any resources to help understand what's going on under the hood? I already have `docker` in my computer, why do I still need `docker-py`? Thanks!

**Comment by tfoote** [comment]
`docker-py` is a python library that helps you invoke docker programmatically. It doesn't replace docker.

**Comment by dongyy1148** [comment]
@tfoote I met the similar problem. I have tried to do pip install --user distro and pip install --user docker-py, but they don't work. Is there any other solution? Thanks a lot!

> Traceback (most recent call last):
  File "/usr/bin/rocker", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'docker' distribution was not found and is required by rocker
