### ISSUE TITLE
Support on macOS

### ISSUE THREAD

**Issue by ericluwj** [osrf/rocker#154]
### Description
It is understood that this tool should work on most systems using with a recent docker version available.
I am not sure whether is macOS supported, but I'm facing an error on macOS when trying out the examples after installing `rocker` using `pip`.
If macOS is not supported, I really hope that it can be.

### Your environment
OS Version: macOS Big Sur 11.5
Python Version: 3.8.11
Docker Version: Docker version 20.10.7, build f0df350

### Steps to reproduce
* Install `rocker` using `pip3`
* Run the following command:
```
~ rocker --x11 --user --home --pull --pulse tfoote/drone_demo
Active extensions ['home', 'pulse', 'x11', 'user']
Traceback (most recent call last):
  File "/usr/local/bin/rocker", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/rocker/cli.py", line 65, in main
    dig = DockerImageGenerator(active_extensions, args_dict, base_image)
  File "/usr/local/lib/python3.8/site-packages/rocker/core.py", line 202, in __init__
    self.dockerfile = generate_dockerfile(active_extensions, self.cliargs, base_image)
  File "/usr/local/lib/python3.8/site-packages/rocker/core.py", line 324, in generate_dockerfile
    dockerfile_str += el.get_snippet(args_dict) + '\n'
  File "/usr/local/lib/python3.8/site-packages/rocker/extensions.py", line 165, in get_snippet
    return em.expand(snippet, self.get_environment_subs())
  File "/usr/local/lib/python3.8/site-packages/rocker/extensions.py", line 157, in get_environment_subs
    self._env_subs['audio_group_id'] = grp.getgrnam('audio').gr_gid
KeyError: "getgrnam(): name not found: 'audio'"
```

**Comment by tfoote** [comment]
If you can extend this to support macOS that would be great. I have not tried it out and don't have a convenient testing platform. But I'm happy to take contributions that make it compatible as long as it doesn't hurt the linux compatibility.
