### ISSUE TITLE
platform detection breaks nvidia plugin if the entrypoint is invalid

### ISSUE THREAD

**Issue by tfoote** [osrf/rocker#43]
This would be more robust if it provided it's own entrypoint.

Backtrace of the error. 
```
$ rocker --x11 --nvidia --user --home --pulse ddm
Plugins found: ['dev_helpers', 'home', 'nvidia', 'pulse', 'user', 'x11']
Active extensions ['home', 'nvidia', 'pulse', 'x11', 'user']
Traceback (most recent call last):
  File "/usr/bin/rocker", line 11, in <module>
    load_entry_point('rocker==0.1.4', 'console_scripts', 'rocker')()
  File "/usr/lib/python3/dist-packages/rocker/cli.py", line 58, in main
    dig = DockerImageGenerator(active_extensions, args_dict, base_image)
  File "/usr/lib/python3/dist-packages/rocker/core.py", line 77, in __init__
    self.dockerfile = generate_dockerfile(active_extensions, self.cliargs, base_image)
  File "/usr/lib/python3/dist-packages/rocker/core.py", line 180, in generate_dockerfile
    dockerfile_str += el.get_preamble(args_dict) + '\n'
  File "/usr/lib/python3/dist-packages/rocker/nvidia_extension.py", line 107, in get_preamble
    return em.expand(preamble, self.get_environment_subs(cliargs))
  File "/usr/lib/python3/dist-packages/rocker/nvidia_extension.py", line 92, in get_environment_subs
    dist, ver, codename = detect_os(cliargs['base_image'])
TypeError: 'NoneType' object is not iterable
```

Example of the error that caused the issue:
```
docker run -it   --rm    -v /home/tfoote:/home/tfoote  -v /run/user/1000/pulse:/run/user/1000/pulse --device /dev/snd  -e PULSE_SERVER=unix:/run/user/1000/pulse/native -v /run/user/1000/pulse/native:/run/user/1000/pulse/native --group-add 29   -e DISPLAY -e TERM   -e QT_X11_NO_MITSHM=1   -e XAUTHORITY=/tmp/.docker.xauth -v /tmp/.docker.xauth:/tmp/.docker.xauth   -v /tmp/.X11-unix:/tmp/.X11-unix   -v /etc/localtime:/etc/localtime:ro    rocker_ddm_home_pulse_x11_user --entrypoint /bin/bash
/entrypoint.sh: 4: .: Can't open /workspace/drone_demo/install/setup.sh
```

**Comment by TakeshiKishita** [comment]
Is there a way to work around this problem?
Do I have to use off-your-rocker?
 Thank you.

**Comment by tfoote** [comment]
Make sure that your entrypoint can execute.

**Comment by meyerj** [comment]
I had the same problem with a base image built from Ubuntu 18.04 Bionic. Nothing special and unrelated to having an entrypoint or not.

It also happens for the [official ros](https://hub.docker.com/_/ros) images from DockerHub:

```sh
$ ~/.local/bin/rocker --pull --nvidia ros:melodic
[...]
b'{"status":"Status: Downloaded newer image for ros:melodic"}\r\n'
docker run -it --rm rocker__detection_ros:melodic
Traceback (most recent call last):
  File "/home/johannes/.local/bin/rocker", line 11, in <module>
    sys.exit(main())
  File "/home/johannes/.local/lib/python3.6/site-packages/rocker/cli.py", line 58, in main
    dig = DockerImageGenerator(active_extensions, args_dict, base_image)
  File "/home/johannes/.local/lib/python3.6/site-packages/rocker/core.py", line 77, in __init__
    self.dockerfile = generate_dockerfile(active_extensions, self.cliargs, base_image)
  File "/home/johannes/.local/lib/python3.6/site-packages/rocker/core.py", line 180, in generate_dockerfile
    dockerfile_str += el.get_preamble(args_dict) + '\n'
  File "/home/johannes/.local/lib/python3.6/site-packages/rocker/nvidia_extension.py", line 107, in get_preamble
    return em.expand(preamble, self.get_environment_subs(cliargs))
  File "/home/johannes/.local/lib/python3.6/site-packages/rocker/nvidia_extension.py", line 92, in get_environment_subs
    dist, ver, codename = detect_os(cliargs['base_image'])
TypeError: 'NoneType' object is not iterable
```

The problem is that the `detect_os` binary [built in container](https://github.com/osrf/rocker/blob/757c48943b259fee47ffd668cd4ca0fd5c582756/src/rocker/os_detector.py#L40) based on image [python:3](https://hub.docker.com/_/python?tab=description) does not work in Bionic because it requires a newer version of libc:

```sh
$ docker run -it --rm rocker__detection_ros:melodic
[6] Error loading Python lib '/tmp/_MEIWTdrFX/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIWTdrFX/libpython3.7m.so.1.0)

$ docker run -it --rm rocker__detection_ros:melodic ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

$ docker run -it --rm python:3 ldd --version
ldd (Debian GLIBC 2.28-10) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

If I replace [this FROM line](https://github.com/osrf/rocker/blob/757c48943b259fee47ffd668cd4ca0fd5c582756/src/rocker/os_detector.py#L24) by `FROM python:3-stretch` it works:
```
$ docker run -it rocker__detection_ros:melodic
('Ubuntu', '18.04', 'bionic')

$ docker run -it python:3-stretch ldd --version
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

But for a base image with an entrypoint this approach also does not work. I am going to submit a pull request to fix it in the coming days. Is switching back to `stretch` a viable solution?
