### ISSUE TITLE
The 'docker' distribution was not found and is required by rocker

### ISSUE THREAD

**Issue by shmily-skx** [osrf/rocker#44]
Traceback (most recent call last):
  File "/usr/bin/rocker", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'docker' distribution was not found and is required by rocker

**Comment by tfoote** [comment]
Can you make sure that you have python3-docker installed? How did you install? What are you running?What platform are you running on?

I noticed this recently in a virtualenv where I had to pip install docker but if you're from debs that shouldn't be required. There's specific logic for trying to pick the right import https://github.com/osrf/rocker/commit/8433976bc39f811100c2e56a2b0bdb6c3c1523b7

**Comment by huberemanuel** [comment]
I faced the same issue, but the error was in ~/.local so I run pip install with '--user' flag and it was able to find the docker package, all working now.

**Comment by dongyy1148** [comment]
@tfoote  I met the similar problem. I have tried to do pip install --user distro and pip install --user docker-py, but they don't work. Is there any other solution? Thanks a lot!

>  Traceback (most recent call last):

    File "/usr/bin/rocker", line 6, in
    from pkg_resources import load_entry_point
    File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/init.py", line 3241, in
    @_call_aside
    File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/init.py", line 3225, in _call_aside
    f(*args, **kwargs)
    File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/init.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
    File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/init.py", line 583, in _build_master
    ws.require(requires)
    File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/init.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
    File "/home/isuzu/.local/lib/python3.5/site-packages/pkg_resources/init.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'docker' distribution was not found and is required by rocker

**Comment by huberemanuel** [comment]
Try  `pip install docker --user`

**Comment by tfoote** [comment]
It sounds like all these are cases where python-docker weren't on the path so as long as that requirement is satisfied I don't think there's a bug here.

**Comment by yapbenzet** [comment]
I had the same error. I tried similar solutions, but the problem was not solved. But I realized that the problem is conda related. If I run rocker --version command after running conda activate command, I get error. After conda deactivate command, rocker works fine.

**Comment by yapbenzet** [comment]
I had the same error. I tried similar solutions but the problem was not solved. But I realized that the problem is conda related. If I run rocker --version command after running conda activate command, I get error. After conda deactivate command, rocker works fine.
