### ISSUE TITLE
focal install missing python3-distutils by default

### ISSUE THREAD

**Issue by tfoote** [osrf/rocker#95]
The quick solution is to `sudo apt install python3-distutils` but it should be declared properly.

**Comment by tfoote** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/rocker", line 33, in <module>
    sys.exit(load_entry_point('rocker==0.2.12', 'console_scripts', 'rocker')())
  File "/usr/bin/rocker", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/rocker/cli.py", line 19, in <module>
    from .core import DockerImageGenerator
  File "/usr/lib/python3/dist-packages/rocker/core.py", line 28, in <module>
    import docker
  File "/usr/lib/python3/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python3/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/lib/python3/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/lib/python3/dist-packages/docker/auth.py", line 7, in <module>
    from . import credentials
  File "/usr/lib/python3/dist-packages/docker/credentials/__init__.py", line 2, in <module>
    from .store import Store
  File "/usr/lib/python3/dist-packages/docker/credentials/store.py", line 9, in <module>
    from .utils import create_environment_dict
  File "/usr/lib/python3/dist-packages/docker/credentials/utils.py", line 1, in <module>
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'
```

It looks like this is actually a missing dependency of docker-py but it's generally available. Though we're actually missing python3-setuptools which would bring it in as a dependency.
